version: "3.8"
services:
  rvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rvc
    volumes:
      - ./weights:/app/assets/weights
      - ./opt:/app/opt
      - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
      - ./logs:/app/logs
    ports:
      - 7865:7865
    shm_size: 8gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tensorboard:
    image: tensorflow/tensorflow:latest
    container_name: tensorboard
    volumes:
      - ./logs:/logs
    ports:
      - 6006:6006
    command: tensorboard --logdir /logs --bind_all